# @name: config.ini
# @creation_date: 2025-02-11
# @license: The MIT License <https://opensource.org/licenses/MIT>
# @author: Simon Bowie <ad7588@coventry.ac.uk>
# @purpose: Contains private config variables
# @acknowledgements:
# https://stackoverflow.com/questions/924700/best-way-to-retrieve-variable-values-from-a-text-file

# OPS API variables
# Hostname for OPS API, usually https://ops.epo.org/
ops_url='https://ops.epo.org/'
# Hostname for OPS API for images for some reason different to above, usually http://ops.epo.org/
ops_url_images='http://ops.epo.org/'
# API credentials from OPS https://developers.epo.org/
consumer_key=''
consumer_secret=''

# Number of documents to retrieve
range_limit = '10'